--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItsMax123/KOTH
build-by-default: true
branches:
- master
projects:
  KOTH:
    path: ""
    icon: "koth.png"
    libs:
      - src: CortexPE/DiscordWebhookAPI/DiscordWebhookAPI
        version: 1.0.1
      - src: CortexPE/Commando/Commando
        version: 2.1.1
      - src: thebigsmilexd/apibossbar/apibossbar
        version: 0.1.5
    lint:
      phpstan: false
...
