---
#Time (IN HOURS) between each KOTH event:
delay_between_koths: 6

#The time (IN SECONDS) to capture KOTH:
capture_time: 300

#The commands that will be executed when the KOTH event has ended, {PLAYER} will be replaced with the name of the winner:
reward_commands:
  - "give {PLAYER} diamond 64"
  - "give {PLAYER} obsidian 64"

#The message that will be broadcasted when a KOTH event starts:
koth_start_message: "§7[§bKOTH§7] §a§lKOTH event has started!"

#The messgae that will be broadcasted when a KOTH event ends, {PLAYER} will be replaced with the name of the winner:
koth_end_message: "§7[§bKOTH§7] §a§lKOTH event has ended and {PLAYER} has won!"

#The coordinates of the KOTH zone (can be edited in-game with '/koth setpos1' and '/koth setpos2')
position1: "0:0:0"
position2: "0:256:0"
...
